version: "3"

services:
  graphTest:
    build: .
    container_name: graphTest
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    ports:
      - "3333:3333"
    networks:
      - playapp-network
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - /home/duducp/PostgreSQL:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

networks:
  playapp-network:
    driver: bridge
