version: "3"

services:
  graphTest:
    build: .
    container_name: graphTest
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    ports:
      - "3333:3333"
    networks:
      - playapp-network
networks:
  playapp-network:
    driver: bridge
